services:
  - name: spotify-additonal-stats-api
    type: web
    runtime: node
    region: virginia
    plan: free
    buildCommand: |
      npm install && npx playwright install --with-deps
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
